remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

title: ğŸ€ğŸŒ±ğŸŒµğŸ½ğŸğŸ¡
author: yakirChen


navbar-links:
  Blog: "/"
  Hire me: "https://yakirchen.github.io"
  Projects: "projects"
  About Me / Contact: "aboutme"

avatar: "/assets/img/deanimg.jpeg"

social-network-links:
  email: "iamyakirchen@outlook.com"
  github: yakirChen

share-links-active:
  twitter: true
  facebook: true
  linkedin: true

excerpt_length: 50
feed_show_excerpt: false
feed_show_tags: false

keywords: "r yakir,r java"

link-col: "#404040"

mobile-theme-col: "#0085A1"

site-css: "/assets/css/custom-styles.css"
site-js: "/assets/js/custom-script.js"

timezone: "Asia/Shanghai"
permalink: /blog/:title/
paginate: 10
paginate_path: "/page:num/"

disqus: "deanattali-site"
google_analytics: "UA-59820529-1"
fb_app_id: "536330676521989"


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      carbonads: true
      comments: true
      social-share: true
      show-share: true
      show-subscribe: true
      support_promo_box: true
      after-content: [share-section.html, scroll-box.html]
  -
    scope:
      path: "notblog"
    values:
      layout: "post"
      carbonads: true
      comments: true
      social-share: true
      show-share: true
      show-subscribe: true
      support_promo_box: true
      after-content: [share-section.html, scroll-box.html]
  -
    scope:
      path: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
    values:
      layout: "page"
      before-content: [support_promo_box.html, carbonads.html]
      footer-extra: footer-subscribe.html

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - docs/
  - files/java/Scrabble/*
