remote_theme: daattali/beautiful-jekyll@5.0.0
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

title: ğŸ€ğŸŒ±ğŸŒµğŸ½ğŸğŸ¡
author: yakirChen

navbar-links:
  Blog: "/"
  Hire me: "https://yakirchen.github.io"
  Projects: "projects"
  About Me: "about"

avatar: "favicon.ico"
round-avatar: true

social-network-links:
  email: "iamyakirchen@outlook.com"
  github: yakirChen

excerpt_length: 50
feed_show_excerpt: false
feed_show_tags: false

keywords: "r yakir,r java"

link-col: "#404040"

mobile-theme-col: "#0085A1"

site-css: "/assets/css/custom-styles.css"
site-js: "/assets/js/custom-script.js"

timezone: "Asia/Shanghai"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 100
paginate_path: "/page:num/"

kramdown:
  input: GFM

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - docs/
  - files/java/Scrabble/*

plugins:
  - jekyll-paginate
  - jekyll-sitemap